### ISSUE TITLE
How do you get the box prompt when training and testing?

### ISSUE THREAD

**Issue by YinqiCai** [ucwxb/I-MedSAM#1]
Hello, thanks for your great work! 
But I have a confusing question: how do you get the box prompt when training and testing? I don't see sth. about this question in the paper. Can you help me with this? Thanks!

**Comment by ucwxb** [comment]
Hi, thanks for your interest in our work. We follow the preprocess of [MedSAM](https://github.com/OpenGVLab/SAM-Med2D/blob/main/utils.py#L15) and [SAM-Med2D](https://github.com/OpenGVLab/SAM-Med2D/blob/main/utils.py#L15) to obtain box prompt.

**Comment by YinqiCai** [comment]
> Hi, thanks for your interest in our work. We follow the preprocess of [MedSAM](https://github.com/OpenGVLab/SAM-Med2D/blob/main/utils.py#L15) and [SAM-Med2D](https://github.com/OpenGVLab/SAM-Med2D/blob/main/utils.py#L15) to obtain box prompt.

thanks for your reply. It makes use of the ground truth mask to obtain prompts, and does so in the testing phase as well, right?

**Comment by ucwxb** [comment]
> > Hi, thanks for your interest in our work. We follow the preprocess of [MedSAM](https://github.com/OpenGVLab/SAM-Med2D/blob/main/utils.py#L15) and [SAM-Med2D](https://github.com/OpenGVLab/SAM-Med2D/blob/main/utils.py#L15) to obtain box prompt.
> 
> thanks for your reply. It makes use of the ground truth mask to obtain prompts, and does so in the testing phase as well, right?

Yes

**Comment by YinqiCai** [comment]
> > > Hi, thanks for your interest in our work. We follow the preprocess of [MedSAM](https://github.com/OpenGVLab/SAM-Med2D/blob/main/utils.py#L15) and [SAM-Med2D](https://github.com/OpenGVLab/SAM-Med2D/blob/main/utils.py#L15) to obtain box prompt.
> > 
> > 
> > thanks for your reply. It makes use of the ground truth mask to obtain prompts, and does so in the testing phase as well, right?
> 
> Yes

I get it, thank you.

**Comment by ucwxb** [comment]
Hi, the code has been released. Please feel free to contact me if you have any questions.
