### ISSUE TITLE
Image size for training and inferencing

### ISSUE THREAD

**Issue by ljmkgbkq** [ucwxb/I-MedSAM#5]
Hello. Are there any requirements for picture sizes for training and reasoning? I see image_size=384 in the code, but this size is a little small for my data set. Thank you

**Comment by ucwxb** [comment]
Hi, the size of the pictures is not restricted. We follow the experiment settings of baseline SwIPE, which set 384 as the resolution of images. You can adjust the two params 'image_size' and 'label_size'  in 'main.py' to fit your dataset.
