### ISSUE TITLE
模型文件

### ISSUE THREAD

**Issue by LecongXiong** [ucwxb/I-MedSAM#6]
您好，我安装readme配置好项目进行训练和测试得到的结果非常差，我不知道是什么原因，您能给我提供您的模型文件吗

**Comment by ucwxb** [comment]
Hi, the pretrained checkpoint on sessile-Kvasir has been provided here: https://drive.google.com/file/d/1qd1FNoc3Io2g8t9HCjaELNYxOHLoiVO0/view?usp=sharing
![image](https://github.com/user-attachments/assets/c9b10aab-40b3-4ae4-a8fa-6c9bdc8dd3cf)

**Comment by LecongXiong** [comment]
好的，谢谢您
